#ifndef INPUT_H
#define INPUT_H

#define KEYMSG_A_BUTTON "A"
#define KEYMSG_B_BUTTON "B"
#define KEYMSG_UP_BUTTON "UP"
#define KEYMSG_DOWN_BUTTON "DOWN"
#define KEYMSG_LEFT_BUTTON "LEFT"
#define KEYMSG_RIGHT_BUTTON "RIGHT"
#define KEYMSG_START_BUTTON "START"
#define KEYMSG_SELECT_BUTTON "SELECT"

#endif