//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bunny_H
#define METASPRITE_bunny_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bunny_TILE_ORIGIN 0
#define bunny_TILE_W 8
#define bunny_TILE_H 8
#define bunny_WIDTH 160
#define bunny_HEIGHT 144
#define bunny_TILE_COUNT 189
#define bunny_PALETTE_COUNT 1
#define bunny_COLORS_PER_PALETTE 4
#define bunny_TOTAL_COLORS 4
#define bunny_MAP_ATTRIBUTES bunny_map_attributes
#define bunny_MAP_ATTRIBUTES_WIDTH 20
#define bunny_MAP_ATTRIBUTES_HEIGHT 18
#define bunny_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define bunny_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(bunny)

extern const palette_color_t bunny_palettes[4];
extern const uint8_t bunny_tiles[3024];

extern const unsigned char bunny_map[360];
extern const unsigned char bunny_map_attributes[360];

#endif
